version: 2
project_name: sst
before:
  hooks:
    - go mod tidy
    - bash -c "cd ./platform && bun run build"
    - go test ./cmd/... ./pkg/...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/sst

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      sst-
      {{- if eq .Os "darwin" }}mac-
      {{- else if eq .Os "windows" }}windows-
      {{- else if eq .Os "linux" }}linux-{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "#86" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "0.0.0-{{ .Timestamp }}"
aurs:
  - homepage: "https://github.com/sst/ion"
    description: "Deploy anything"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/sst-bin.git'
    license: "MIT"
    package: |-
      install -Dm755 ./sst "${pkgdir}/usr/bin/sst"
brews:
  - repository:
      owner: sst
      name: homebrew-tap
nfpms:
  - maintainer: sst
    description: the sst cli
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}mac
      {{- else }}{{ .Os }}{{ end }}-{{ .Arch }}

# scoop:
#   bucket:
#     owner: sst
#     name: scoop-bucket
#   homepage: "https://github.com/sst/ion"
#   description: "sst cli"
#   license: Apache 2.0

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'
      - '^ci:'

