#!/bin/bash
set -euo pipefail
APP=sst

os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m)

filename="$APP-$os-$arch.tar.gz"

if [[ "$filename" == *"-linux-"* && "$arch" != "x86_64" && "$arch" != "arm64" && "$arch" != "i386" ]] || \
[[ "$filename" == *"-darwin-"* && "$arch" != "x86_64" && "$arch" != "arm64" ]] || \
[[ "$filename" != *"-linux-"* && "$filename" != *"-darwin-"* ]]; then
    echo "unsupported os or architecture: $os $arch"
    exit 1
fi

INSTALL_DIR=$HOME/.sst/bin
mkdir -p $INSTALL_DIR

url="https://github.com/sst/ion/releases/latest/download/$filename"

# Check if sst is already in the PATH
if command -v sst >/dev/null 2>&1; then
    installed_version=$(sst version)
    
    latest_version=$(curl -s https://api.github.com/repos/sst/ion/releases/latest | grep -oP '(?<="tag_name": ")[^"]+' | sed 's/^v//')
    
    if [[ "$installed_version" != "$latest_version" ]]; then
        read -p "Do you want to download the latest version? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    else
        echo "Already installed: $installed_version"
        exit 0
    fi
fi

echo "Downloading $filename from $url"
mkdir -p ssttmp && cd ssttmp
curl -# -L $url | tar xz
mv sst $INSTALL_DIR
cd .. && rm -rf ssttmp

# Add the directory to the PATH
add_to_path() {
    local config_file=$1
    local command=$2
    
    if [[ -w $config_file ]]; then
        echo -e "\n# sst" >> "$config_file"
        echo "$command" >> "$config_file"
        echo "Added $INSTALL_DIR to PATH in $config_file"
    else
        echo "manually add the directory to $config_file (or similar):"
        echo "  $command"
    fi
}

if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    case $(basename "$SHELL") in
        fish)
            add_to_path "$HOME/.config/fish/config.fish" "fish_add_path $INSTALL_DIR"
        ;;
        zsh)
            add_to_path "$HOME/.zshrc" "export PATH=$INSTALL_DIR:\$PATH"
        ;;
        bash)
            add_to_path "$HOME/.bashrc" "export PATH=$INSTALL_DIR:\$PATH"
        ;;
        *)
            echo 'manually add the directory to ~/.bashrc (or similar):'
            echo "  export PATH=$INSTALL_DIR:\$PATH"
        ;;
    esac
fi

# Add the directory containing the sst binary to the PATH in GitHub Actions
if [ -n "${GITHUB_ACTIONS-}" ] && [ "${GITHUB_ACTIONS}" == "true" ]; then
    echo "$INSTALL_DIR" >> $GITHUB_PATH
f