/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "Hono": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
  }
}
// cloudflare 
declare module "sst" {
  export interface Resource {
    "MyBucket": import("@cloudflare/workers-types").R2Bucket
  }
}
